routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    // Route Dashboards
    Route::get('homes', 'HomeController@index')->name('homes.index');

    // Route Stuffs
    Route::resource('stuffs', 'StuffController');

    // Route Types Stuff
    Route::resource('types_stuff', 'TypeStuffController');

    // Route Suppliers
    Route::resource('suppliers', 'SupplierController');

    // Route Countries
    Route::resource('countries', 'CountryController');

    // Route Provinces
    Route::resource('provinces', 'ProvinceController'); 

    // Route Provinces
    Route::resource('sellings', 'SellingController');

    Route::get('sellings/{id}', 'SellingController@shows')->name('sellings.shows');
});

resources/views/footer_javascript.blade.php
<!-- jQuery -->
<script src="{{asset('gentelellaassets/vendors/jquery/dist/jquery.min.js')}}"></script>
        
<!-- Bootstrap -->
<script src="{{asset('gentelellaassets/vendors/bootstrap/dist/js/bootstrap.min.js')}}"></script>

<!-- FastClick -->
<script src="{{asset('gentelellaassets/vendors/fastclick/lib/fastclick.js')}}"></script>

<!-- NProgress -->
<script src="{{asset('gentelellaassets/vendors/nprogress/nprogress.js')}}"></script>

<!-- Chart.js -->
<script src="{{asset('gentelellaassets/vendors/Chart.js/dist/Chart.min.js')}}"></script>

<!-- gauge.js -->
<script src="{{asset('gentelellaassets/vendors/gauge.js/dist/gauge.min.js')}}"></script>

<!-- bootstrap-progressbar -->
<script src="{{asset('gentelellaassets/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js')}}"></script>

<!-- iCheck -->
<script src="{{asset('gentelellaassets/vendors/iCheck/icheck.min.js')}}"></script>

<!-- Skycons -->
<script src="{{asset('gentelellaassets/vendors/skycons/skycons.js')}}"></script>

<!-- Flot -->
<script src="{{asset('gentelellaassets/vendors/Flot/jquery.flot.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/Flot/jquery.flot.pie.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/Flot/jquery.flot.time.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/Flot/jquery.flot.stack.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/Flot/jquery.flot.resize.js')}}"></script>

<!-- Flot plugins -->
<script src="{{asset('gentelellaassets/vendors/flot.orderbars/js/jquery.flot.orderBars.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/flot-spline/js/jquery.flot.spline.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/flot.curvedlines/curvedLines.js')}}"></script>

<!-- DateJS -->
<script src="{{asset('gentelellaassets/vendors/DateJS/build/date.js')}}"></script>

<!-- JQVMap -->
<script src="{{asset('gentelellaassets/vendors/jqvmap/dist/jquery.vmap.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/jqvmap/dist/maps/jquery.vmap.world.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js')}}"></script>

<!-- bootstrap-daterangepicker -->
<script src="{{asset('gentelellaassets/vendors/moment/min/moment.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/bootstrap-daterangepicker/daterangepicker.js')}}"></script>

<!-- Datatables -->
<script src="{{asset('gentelellaassets/vendors/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/datatables.net-buttons/js/buttons.flash.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/datatables.net-scroller/js/dataTables.scroller.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/jszip/dist/jszip.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/pdfmake/build/pdfmake.min.js')}}"></script>
<script src="{{asset('gentelellaassets/vendors/pdfmake/build/vfs_fonts.js')}}"></script>

<!-- Custom Theme Scripts -->
<script src="{{asset('gentelellaassets/builds/js/custom.min.js')}}"></script>
<script>
    // For Adding and Deleting New Row start -----------------------------------------------------------
    $(document).ready(function(){
        $('.btn').click(function(){
            var id = $(this).data('id');
            var URL = $(this).data('href');

            $.ajax({
                type: 'GET',
                url: 'http://localhost/pos/public/stuffs_out/1',
                data: {id: id},

                success:function(data){
                    console.log(data);
                }
            });
            return false;
        });
        var i = 0;
        $(".add-row").click(function(){  
            i++;
            var html  = "";
            html     += '<tr><td><input id="row'+i+'" type="checkbox" name="record[]" class="flat" /></td><td>';		
            html     += "<input type='text' name='stuff_id' id='stuff_id' class='form-control row"+i+"' />";
            html     += "<td><input type='number' class='form-control row"+i+"'></td></tr>";			
    
            $("table tbody#emp_details").append(html);
        });
    
        // Find and remove selected table rows
        $(".delete-row").click(function()
        {
            var row_count         = $("#emp_details").find('input[name="record[]"]').length;
            var checked_row_count = $('[name="record[]"]:checked').length;
    
            if(row_count != checked_row_count)
            {
                $("#emp_details").find('input[name="record[]"]').each(function()
                {
                    if($(this).is(":checked"))
                    {
                        $(this).parents("#emp_details tr").remove();
                    }
                });
            } else {
                alert("All rows can't be deleted");
                return false;
            }
        });	
    }); 
    // For Adding and Deleting New Row close ----------------------------------------------------------->

    $('#datatable-stuffs').dataTable( {
        "order": [],
        "columnDefs": [{
            "targets"  : [0, 4],
            "orderable": false,
        }]
    });

    $('#datatable-types_stuff').dataTable({
        "order": [],
        "columnDefs": [{
            "targets"  : [0, 3],
            "orderable": false,
        }]
    });

    $('#datatable-suppliers').dataTable({
        "order": [],
        "columnDefs": [{
            "targets"  : [0, 1, 3],
            "orderable": false,
        }]
    });

    $('#datatable-selling').dataTable({
        "order": [],
        "columnDefs": [{
            "targets"  : [0, 1, 3],
            "orderable": false,
        }]
    });

    $('#datatable-provinces').dataTable({
        "order": [],
        "pageLength": 5,
        "columnDefs": [{
            "targets"  : [0, 1, 3],
            "orderable": false,
        }]
    });

    $('#datatable-countries').dataTable({
        "order": [],
        "pageLength": 5,
        "columnDefs": [{
            "targets"  : [0, 1, 3],
            "orderable": false,
        }]
    });
</script>

resources/views/header.blade.php
{{-- start top-nav --}}
<div class="top_nav">

    {{-- start nav_menu --}}
    <div class="nav_menu">
        <nav>
            {{-- start nav toggle --}}
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            {{-- end nav toggle --}}

            {{-- start nav --}}
            <ul class="nav navbar-nav navbar-right">

                <li>
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="{{asset('gentelellaassets/productions/images/img.jpg')}}" alt="">{{Auth::user()->name}}
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="javascript:;"> Profile</a></li>
                        <li>
                            <a href="javascript:;">
                                <span class="badge bg-red pull-right">50%</span>
                                <span>Settings</span>
                            </a>
                        </li>
                        <li><a href="javascript:;">Help</a></li>
                        <li>
                            <a class="dropdown-item" href="{{route('logout')}}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"> {{ __('Logout') }}</a>
                            <form id="logout-form" action="{{route('logout')}}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </li>
                
            </ul>
            {{-- end nav --}}
        </nav>

    </div>
    {{-- end nav_menu --}}

</div>
{{-- end top-nav --}}

resources/views/home.blade.php
@extends('layouts.app')
@section('title', 'SMART-POS | Home')
@section('home_content')
{{-- start right_col --}}
<div class="right_col" role="main">
    
    {{-- start row title_count --}}
    <div class="row tile_count">

        {{-- start col --}}
        <div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Total Buyer</span>
            <div class="count">2500</div>
            <span class="count_bottom"><i class="green">4% </i> From last Week</span>
        </div>
        {{-- end col --}}

        {{-- start col --}}
        <div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Stock Stuffs</span>
            <div class="count">2,315</div>
            <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
        </div>
        {{-- end col --}}

        {{-- start col --}}
        <div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-clock-o"></i> Total Stuffs Out </span>
            <div class="count">123.50</div>
            <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>3% </i> From last Week</span>
        </div>
        {{-- end col --}}

        {{-- start col --}}
        <div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Total Income</span>
            <div class="count green">Rp. 10,000.000</div>
            <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
        </div>
        {{-- end col --}}

    </div>
    {{-- end row title_count --}}

</div>
{{-- end right_col --}}
@endsection

resources/views/sidebar.blade.php
{{-- start col --}}
<div class="col-md-3 left_col">

    {{-- start left-col --}}
    <div class="left_col scroll-view">
        
        {{-- start navbar --}}
        <div class="navbar nav_title" style="border: 0;">
            <a href="{{route('homes.index')}}" class="site_title"><span>SMART-POS</span></a>
        </div>

        <div class="clearfix"></div>

        {{-- start profile --}}
        <div class="profile clearfix">
            
            {{-- start profile_pic --}}
            <div class="profile_pic">
                <img src="{{asset('gentelellaassets/productions/images/img.jpg')}} " alt="..." class="img-circle profile_img" />
            </div>
            {{-- end profile_pic --}}
            
            {{-- start profile_info --}}
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{Auth::user()->name}}</h2>
            </div>
            {{-- end profile_pic --}}
        
        </div>
        {{-- end profile --}}

        <br />

        {{-- start sidebar-menu --}}
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

            {{-- start menu_section --}}
            <div class="menu_section">
                <ul class="nav side-menu">
                    <li><a><span class="glyphicon glyphicon-briefcase"></span> Transactions<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="index1.html">Stuffs In (Order)</a></li>
                            <li class="{{request()->is('sellings/*') ? 'current-page' : ''}}"><a href="{{route('sellings.index')}}">Stuffs Out</a></li>
                        </ul>
                    </li> 

                    <li class="{{request()->path() ? 'active' : ''}}"><a><span class="glyphicon glyphicon-hdd"></span> Master Stuff<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu" style="{{request()->path() ? 'display: block;' : 'display: none;'}}">
                            <li class="{{request()->is('stuffs/*') ? 'current-page' : ''}}"><a href="{{route('stuffs.index')}}">Stuffs</a></li>
                            <li class="{{request()->is('types_stuff/*') ? 'current-page' : ''}}"><a href="{{route('types_stuff.index')}}">Types Stuff</a></li>
                        </ul>
                    </li> 
                    
                    <li class="{{request()->path() ? 'active' : ''}}"><a><span class="glyphicon glyphicon-hdd"></span> Master Data<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu" style="{{request()->path() ? 'display: block;' : 'display: none;'}}">
                            <li class="{{request()->is('countries/*') ? 'current-page' : ''}}"><a href="{{route('countries.index')}}">Countries</a></li>
                            <li class="{{request()->is('provinces/*') ? 'current-page' : ''}}"><a href="{{route('provinces.index')}}">Provinces</a></li>
                            <li class="{{request()->is('suppliers/*') ? 'current-page' : ''}}"><a href="{{route('suppliers.index')}}">Suppliers</a></li>
                        </ul>
                    </li>  
                </ul>
            </div>
            {{-- end menu section --}}

        </div>
        {{-- end sidebar-menu --}}

    </div>
    {{-- end left-col --}}

</div>
{{-- end col --}}