routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    // Route Dashboards
    Route::get('homes', 'HomeController@index')->name('homes.index');

    // Route Stuffs
    Route::resource('stuffs', 'StuffController');

    // Route Types Stuff
    Route::resource('types_stuff', 'TypeStuffController');

    // Route Suppliers
    Route::resource('suppliers', 'SupplierController');

    // Route Countries
    Route::resource('countries', 'CountryController');

    // Route Provinces
    Route::resource('provinces', 'ProvinceController'); 

    // Route Provinces
    Route::resource('sellings', 'SellingController');

    Route::get('sellings/{id}', 'SellingController@shows')->name('sellings.shows');
});

app/Models/Stuff.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Stuff extends Model
{
    //
    protected $fillable = [
        'name', 'stock', 'price', 'type_stuff_id'
    ];
    
    public $timestamps = true;

    /**
     * Get the type_stuff for the stuff.
     */
    public function type_stuff()
    {
        return $this->belongsTo('App\Models\TypeStuff');
    }
}

app/Http/Controllers/StuffController.php
<?php

namespace App\Http\Controllers;

use App\Models\Stuff;
use App\Models\TypeStuff;

// use Illuminate\Http\Request;
use App\Http\Requests\StuffsRequest;

class StuffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Show all data Stuff
        $stuffs = Stuff::all();

        // Show all data Types Stuff
        $types_stuff = TypeStuff::all();

        return view('stuff/content', compact('stuffs', 'types_stuff'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StuffsRequest $request)
    {
        // Get result of validate
        $dataInput = $request->validated();

        // If can't running store process
        if (!Stuff::create($dataInput)) {
            // Showing notification error
	        return back()->with('notification_error', 'Stuff with name ' . '<b>' . $dataInput['name'] . '</b>' . ' can\'t saved. Please try again!');
	    }
    	return redirect('stuffs')->with('notification_success', 'Stuff with name <b>' . $dataInput['name'] . '</b> has been successfully saved.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // Retrieve the first model matching the query constraints
        $stuff = Stuff::where('id', $id)->first();

        return view('stuff/detail', compact('stuff'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // Retrieve the first model matching the query constraints
        $stuff = Stuff::where('id', $id)->first();

        // Show all data Types Stuff
        $types_stuff = TypeStuff::all();

        return view('stuff/edit', compact('stuff', 'types_stuff'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StuffsRequest $request, $id)
    {
        // Retrieve the first model matching the query constraints
        $stuff = Stuff::where('id', $id)->first();

        // Get result of validate
        $dataUpdate = $request->validated();

        // If can't running store process
        if (!$stuff->update($dataUpdate)) {
            // Showing notification error
	        return back()->with('notification_error', 'Stuff with name ' . '<b>' . $stuff['name'] . '</b>' . ' can\'t updated. Please try again!');
	    }
    	return redirect()->route('stuffs.show', $id)->with('notification_success', 'Stuff with name <b>' . $stuff['name'] . '</b> has been successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Retrieve the first model matching the query constraints
        $stuff = Stuff::where('id', $id)->first();

        // If can't running delete process
        if (!$stuff->delete()) {
            // Showing notification error
			return redirect('stuffs')->with('notification_error', 'Stuff with name <b>' . $stuff['name'] . '</b> can\'t deleted. Please try again!');
		}
        return redirect('stuffs')->with('notification_success', 'Stuff with name <b>' . $stuff['name'] . '</b> has been successfully deleted.');
    }
}

resources/views/stuff/content.blade.php
@extends('layouts.app')
@section('title', 'POS-SMART | Stuffs')
@section('stuff_content')
{{-- start right_col --}}
<div class="right_col" role="main">

    {{-- start row --}}
    <div class="row">

        {{-- start col --}}
        <div class="col-xs-12 col-sm-12 col-md-12">

            {{-- start breadcrumb --}}
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" style="background: #e9ecef !important;">
                    <li class="breadcrumb-item"><a class="white-text" href="#">Dashboard</a></li>
                    <li class="breadcrumb-item">Master Data</li>
                    <li class="breadcrumb-item active">Stuff</li>
                </ol>
            </nav>
            {{-- end breadcrumb --}}

            {{-- Showing error when running validate process --}}
            @foreach($errors->all() as $message)
                <div class="alert alert-warning">
                    {{$message}}
                </div>
            @endforeach

            <!-- Notification -->
            @if (session('notification_error'))
                <div class="alert alert-danger">
                    {!! session('notification_error') !!}
                </div>
            @endif
            @if (session('notification_success'))
                <div class="alert alert-success">
                    {!! session('notification_success') !!}
                </div>
            @endif

            {{-- start x_panel --}}
            <div class="x_panel">

                {{-- start x_title --}}
                <div class="x_title">

                    <h1>{!! '<b>Stuffs</b>' !!}</h1>
                    
                    <div class="clearfix"></div>
                    
                </div>
                {{-- end x_title --}}

                {{-- start x_content --}}
                <div class="x_content">

                    {{-- start tabpanel --}}
                    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">List</a></li>
                        <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Create </a></li>
                    </ul>
                    {{-- end tabpanel --}}

                    {{-- start myTabContent --}}
                    <div id="myTabContent" class="tab-content">

                        {{-- start tabpanel --}}
                        <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                            <table id="datatable-stuffs" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th style="width: 5%; text-align: center">No</th>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Stock</th>
                                        <th style="width: 10%; text-align: center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($stuffs as $item)
                                    <tr>
                                        <td style="text-align: center">{{$loop->iteration}}</td>
                                        <td>{{$item->name}}</td>
                                        <td>{{$item->price}}</td>
                                        <td>{{$item->stock}}</td>
                                        <td style="text-align: center">
                                            <a href="{{route('stuffs.show', $item->id)}}" role="button" class="btn btn-xs btn-info">View</a>
                                            <a href="{{route('stuffs.edit', $item->id)}}" role="button" class="btn btn-xs btn-primary">Edit</a>
                                            {{Form::open(['route' => ['stuffs.destroy', $item->id], 'class' => 'form-horizontal', 'style' => 'display: -webkit-inline-box'])}}
                                            {{method_field('DELETE')}}
                                            {{Form::button('Delete', ['type' => 'submit', 'class' => 'btn btn-xs btn-danger', 'style' => 'position: relative; top: -4px;', 'onclick' => 'return confirm("You sure to delete this data?")'])}}
                                            {{Form::close()}}
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        {{-- end tabpanel --}}
                        
                        {{-- start tabpanel --}}
                        <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                            {{Form::open(['route' => 'stuffs.store', 'class' => 'form-horizontal form-label-left', 'data-parsley-validate'])}}
                            <div class="form-group">
                                {{Form::label('name', 'Name', ['class' => 'control-label col-md-4 col-sm-5 col-xs-12'])}}
                                <div class="col-xs-12 col-sm-12 col-md-4">
                                    {{Form::text('name', NULL, ['id' => 'name', 'class' => 'form-control col-md-7 col-xs-12'])}}
                                </div>
                            </div>
                            <div class="form-group">
                                {{Form::label('price', 'Price', ['class' => 'control-label col-md-4 col-sm-3 col-xs-12'])}}
                                <div class="col-xs-12 col-sm-12 col-md-4">
                                    {{Form::number('price', NULL, ['id' => 'price', 'class' => 'form-control col-md-7 col-xs-12'])}}
                                </div>
                            </div>
                            <div class="form-group">
                                {{Form::label('stock', 'Stock', ['class' => 'control-label col-md-4 col-sm-3 col-xs-12'])}}
                                <div class="col-xs-12 col-sm-12 col-md-4">
                                    {{Form::number('stock', NULL, ['id' => 'stock', 'class' => 'form-control col-md-7 col-xs-12'])}}
                                </div>
                            </div>
                            <div class="form-group">
                                {{Form::label('type_stuff_id', 'Types Stuff', ['class' => 'control-label col-md-4 col-sm-3 col-xs-12'])}}
                                <div class="col-xs-12 col-sm-12 col-md-4">
                                    <select name="type_stuff_id" id="type_stuff_id" class="form-control col-md-7 col-xs-12">
                                        <option value="">Choose...</option>
                                        @foreach ($types_stuff as $item)
                                            <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            {{Form::button('Submit', ['type' => 'submit', 'class' => 'btn btn-success'])}}
                            {{Form::close()}}
                        </div>
                        {{-- end tabpanel --}}

                    </div>
                    {{-- end myTabContent --}}

                </div>
                {{-- end x_content --}}

            </div>
            {{-- end x_panel --}}

        </div>
        {{-- end col --}}

    </div>
    {{-- end row --}}

</div>
{{-- end right_col --}}
@endsection

resources/views/stuff/detail.blade.php
@extends('layouts.app')
@section('title', 'POS-SMART | ' .$stuff->name)
@section('stuff_content')
{{-- start right_col --}}
<div class="right_col" role="main">

    {{-- start row --}}
    <div class="row">
    
        {{-- start col --}}
        <div class="col-xs-12 col-sm-12 col-md-12">
            
            {{-- start breadcrumb --}}
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" style="background: #e9ecef !important;">
                    <li class="breadcrumb-item"><a class="white-text" href="#">Dashboard</a></li>
                    <li class="breadcrumb-item">Master Data</li>
                    <li class="breadcrumb-item">Stuffs</li>
                    <li class="breadcrumb-item active">Detail</li>
                </ol>
            </nav>
            {{-- end breadcrumb --}}

            <!-- Notification -->
            @if (session('notification_error'))
                <div class="alert alert-danger">
                    {!! session('notification_error') !!}
                </div>
            @endif
            @if (session('notification_success'))
                <div class="alert alert-success">
                    {!! session('notification_success') !!}
                </div>
            @endif

            <a href="{{route('stuffs.index')}}" class="btn btn-lg btn-default" role="button">Back</a>
            <a href="{{route('stuffs.edit', $stuff->id)}}" class="btn btn-lg btn-primary" role="button">Edit</a>
            {{Form::open(['route' => ['stuffs.destroy', $stuff->id], 'class' => 'form-horizontal', 'style' => 'display: -webkit-inline-box'])}}
            {{method_field('DELETE')}}
            {{Form::button('Delete', ['type' => 'submit', 'class' => 'btn btn-lg btn-danger', 'style' => 'position: relative; top: -15px;', 'onclick' => 'return confirm("You sure to delete this data?")'])}}
            {{Form::close()}}

            {{-- start x_panel --}}
            <div class="x_panel">
    
                {{-- start x_title --}}
                <div class="x_title">
    
                    <h1>{!! '<b>'.$stuff->name.'</b>' !!}</h1>
                        
                    <div class="clearfix"></div>
                        
                </div>
                {{-- end x_title --}}
    
                {{-- start x_content --}}
                <div class="x_content">

                    {{-- start div --}}
                     <div>
                        <h4>Stuff Information</h4>
                                
                        <div class="clearfix"></div>   
                    </div>
                    {{-- end div --}}
    
                    <table class="table table-striped table-bordered dt-responsive">
                        <tr>
                            <td style="text-align: right; width: 45%">Name</td>
                            <td>{{$stuff->name}}</td>
                        </tr>
                        <tr>
                            <td style="text-align: right">Price</td>
                            <td>{{$stuff->price}}</td>
                        </tr>
                        <tr>
                            <td style="text-align: right">Stock</td>
                            <td>{{$stuff->stock}}</td>
                        </tr>
                        <tr>
                            <td style="text-align: right">Type Stuff</td>
                            <td>{{$stuff->type_stuff->name}}</td>
                        </tr>
                    </table>

                    {{-- start div --}}
                     <div>
                        <h4>Stuff Information II</h4>
                                    
                        <div class="clearfix"></div>   
                    </div>
                    {{-- end div --}}
        
                    <table class="table table-striped table-bordered dt-responsive">
                        <tr>
                            <td style="text-align: right; width: 45%">Created at</td>
                            <td>{{$stuff->created_at}}</td>
                        </tr>
                        <tr>
                            <td style="text-align: right">Updated at</td>
                            <td>{{$stuff->updated_at}}</td>
                        </tr>
                    </table>
    
                </div>
                {{-- end x_content --}}
    
            </div>
            {{-- end x_panel --}}
    
        </div>
        {{-- end col --}}
    
    </div>
    {{-- end row --}}
    
</div>
{{-- end right_col --}}
@endsection

resources/views/stuff/edit.blade.php
@extends('layouts.app')
@section('title', 'POS-SMART | ' .$stuff->name. " | Edit")
@section('stuff_content')
{{-- start right_col --}}
<div class="right_col" role="main">

    {{-- start row --}}
    <div class="row">
    
        {{-- start col --}}
        <div class="col-xs-12 col-sm-12 col-md-12">

            {{-- start breadcrumb --}}
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" style="background: #e9ecef !important;">
                    <li class="breadcrumb-item"><a class="white-text" href="{{route('homes.index')}}">Home</a></li>
                    <li class="breadcrumb-item">Master Data</li>
                    <li class="breadcrumb-item"><a href="{{route('suppliers.index')}}">stuff</a></li>
                    <li class="breadcrumb-item"><a href="{{route('suppliers.show', $stuff->id)}}">{{$stuff->name}}</a></li>
                    <li class="breadcrumb-item active">Edit</li>
                </ol>
            </nav>
            {{-- end breadcrumb --}}
        
            {{-- Showing error when running validate process --}}
            @foreach($errors->all() as $message)
                <div class="alert alert-warning">
                    {{$message}}
                </div>
            @endforeach
    
            {{-- start x_panel --}}
            <div class="x_panel">
    
                {{-- start x_title --}}
                <div class="x_title">
    
                    <h1>{!! '<b>'.$stuff->name.'</b>' !!}</h1>
                        
                    <div class="clearfix"></div>
                        
                </div>
                {{-- end x_title --}}
    
                {{-- start x_content --}}
                <div class="x_content">

                    {{-- start div --}}
                    <div>
                        <h4>Stuff Information</h4>
                                
                        <div class="clearfix"></div>   
                    </div>
                    {{-- end div --}}
    
                    {{Form::model($stuff, ['route' => ['stuffs.update', $stuff->id], 'class' => 'form-horizontal form-label-left', 'data-parsley-validate'])}}
                    {{method_field('PUT')}}
                    <div class="form-group">
                        {{Form::label('name', 'Name', ['class' => 'control-label col-md-4 col-sm-5 col-xs-12'])}}
                        <div class="col-xs-12 col-sm-12 col-md-4">
                            {{Form::text('name', NULL, ['id' => 'name', 'class' => 'form-control col-md-7 col-xs-12'])}}
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('price', 'Price', ['class' => 'control-label col-md-4 col-sm-3 col-xs-12'])}}
                        <div class="col-xs-12 col-sm-12 col-md-4">
                            {{Form::number('price', NULL, ['id' => 'price', 'class' => 'form-control col-md-7 col-xs-12'])}}
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('stock', 'Stock', ['class' => 'control-label col-md-4 col-sm-3 col-xs-12'])}}
                        <div class="col-xs-12 col-sm-12 col-md-4">
                            {{Form::number('stock', NULL, ['id' => 'stock', 'class' => 'form-control col-md-7 col-xs-12'])}}
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('type_stuff_id', 'Types Stuff', ['class' => 'control-label col-md-4 col-sm-3 col-xs-12'])}}
                        <div class="col-xs-12 col-sm-12 col-md-4">
                            <select name="type_stuff_id" id="type_stuff_id" class="form-control col-md-7 col-xs-12">
                                 <option value="">Choose...</option>
                                @foreach ($types_stuff as $item)
                                    @if ($stuff->type_stuff_id == $item->id)
                                        <option value="{{$item->id}}" selected>{{$item->name}}</option>
                                    @else
                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    {{Form::button('Submit', ['type' => 'submit', 'class' => 'btn btn-success'])}}
                    <a href="{{route('stuffs.show', $stuff->id)}}" class="btn btn-md btn-default" role="button">Back</a>
                    {{Form::close()}}
    
                </div>
                {{-- end x_content --}}
    
            </div>
            {{-- end x_panel --}}
    
        </div>
        {{-- end col --}}
    
    </div>
    {{-- end row --}}
    
</div>
{{-- end right_col --}}
@endsection