routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    // Route Dashboards
    Route::get('homes', 'HomeController@index')->name('homes.index');

    // Route Stuffs
    Route::resource('stuffs', 'StuffController');

    // Route Types Stuff
    Route::resource('types_stuff', 'TypeStuffController');

    // Route Suppliers
    Route::resource('suppliers', 'SupplierController');

    // Route Countries
    Route::resource('countries', 'CountryController');

    // Route Provinces
    Route::resource('provinces', 'ProvinceController'); 

    // Route Provinces
    Route::resource('sellings', 'SellingController');

    Route::get('sellings/{id}', 'SellingController@shows')->name('sellings.shows');
});

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    protected $fillable = [
        'is_active', 'name', 'address', 'phone', 'email', 'province_id'
    ];
    
    public $timestamps = true;

    public function province()
    {
        return $this->BelongsTo('App\Models\Province');
    }
}

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    //
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Models\Supplier;
use App\Models\Province;

// use Illuminate\Http\Request;
use App\Http\Requests\SuppliersRequest;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Show all data Suppliers
        $suppliers = Supplier::all();

        // Show all data Province
        $provinces = Province::all();

        return view('supplier/content', compact('suppliers', 'provinces'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SuppliersRequest $request)
    {
        // Get result of validate
        $dataInput = $request->validated();

        // If can't running store process
        if (!Supplier::create($dataInput)) {
            // Showing notification error
	        return back()->with('notification_error', 'Supplier with name ' . '<b>' . $dataInput['name'] . '</b>' . ' can\'t saved. Please try again!');
	    }
    	return redirect('suppliers')->with('notification_success', 'Supplier with name <b>' . $dataInput['name'] . '</b> has been successfully saved.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // Retrieve the first model matching the query constraints
        $supplier = Supplier::where('id', $id)->first();
        
        return view('supplier/detail', compact('supplier'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // Retrieve the first model matching the query constraints
        $supplier = Supplier::where('id', $id)->first();

        // Show all data Province
        $provinces = Province::all();

        return view('supplier/edit', compact('supplier', 'provinces'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SuppliersRequest $request, $id)
    {
        // Retrieve the first model matching the query constraints
        $supplier = Supplier::where('id', $id)->first();
        
        // Get result of validate
        $dataUpdate = $request->validated();

        if($request->input('is_active') == null){
            $dataUpdate['is_active'] = 0;
        } else{
            $dataUpdate['is_active'] = 1;
        }

        // If can't running store process
        if (!$supplier->update($dataUpdate)) {
            // Showing notification error
	        return back()->with('notification_error', 'Supplier with name ' . '<b>' . $supplier['name'] . '</b>' . ' can\'t updated. Please try again!');
	    }
    	return redirect()->route('suppliers.show', $id)->with('notification_success', 'Supplier with name <b>' . $supplier['name'] . '</b> has been successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Retrieve the first model matching the query constraints
        $stuff = TypeStuff::where('id', $id)->first();

        // If can't running delete process
        if (!$stuff->delete()) {
            // Showing notification error
			return redirect('types_stuff')->with('notification_error', 'Type Stuff with code <b>' . $stuff['code'] . '</b> can\'t deleted. Please try again!');
		}
        return redirect('types_stuff')->with('notification_success', 'Type Stuff with code <b>' . $stuff['code'] . '</b> has been successfully deleted.');
    }
}

resources/views/supplier/content.blade.php
@extends('layouts.app')
@section('title', 'POS-SMART | Suppliers')
@section('supplier_content')
{{-- start right_col --}}
<div class="right_col" role="main">

    {{-- start row --}}
    <div class="row">

        {{-- start col --}}
        <div class="col-xs-12 col-sm-12 col-md-12">
            
            {{-- start breadcrumb --}}
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" style="background: #e9ecef !important;">
                    <li class="breadcrumb-item"><a class="white-text" href="{{route('homes.index')}}">Home</a></li>
                    <li class="breadcrumb-item">Master Data</li>
                    <li class="breadcrumb-item active">Suppliers</li>
                </ol>
            </nav>
            {{-- end breadcrumb --}}

            {{-- Showing error when running validate process --}}
            @foreach($errors->all() as $message)
                <div class="alert alert-warning">
                    {{$message}}
                </div>
            @endforeach

            <!-- Notification -->
            @if (session('notification_error'))
                <div class="alert alert-danger">
                    {!! session('notification_error') !!}
                </div>
            @endif
            @if (session('notification_success'))
                <div class="alert alert-success">
                    {!! session('notification_success') !!}
                </div>
            @endif

            {{-- start x_panel --}}
            <div class="x_panel">

                {{-- start x_title --}}
                <div class="x_title">

                    <h1>{!! '<b>Suppliers</b>' !!}</h1>
                    
                    <div class="clearfix"></div>
                    
                </div>
                {{-- end x_title --}}

                {{-- start x_content --}}
                <div class="x_content">

                    {{-- start tabpanel --}}
                    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">List</a></li>
                        <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Create </a></li>
                    </ul>
                    {{-- end tabpanel --}}

                    {{-- start myTabContent --}}
                    <div id="myTabContent" class="tab-content">

                        {{-- start tabpanel --}}
                        <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                            <table id="datatable-suppliers" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th style="width: 5%; text-align: center">No</th>
                                        <th style="width: 10%; text-align: center">Is Active?</th>
                                        <th>Name</th>
                                        <th style="width: 10%; text-align: center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($suppliers as $item)
                                    <tr>
                                        <td style="text-align: center">{{$loop->iteration}}</td>
                                        <td style="text-align: center">
                                            @if ($item->is_active == 1)
                                                <span class="btn btn-xs btn-success">Active</span>
                                            @else
                                                <span class="btn btn-xs btn-danger">No Active</span>
                                            @endif
                                        </td>
                                        <td>{{$item->name}}</td>
                                        <td style="text-align: center">
                                            <a href="{{route('suppliers.show', $item->id)}}" role="button" class="btn btn-xs btn-info">View</a>
                                            <a href="{{route('suppliers.edit', $item->id)}}" role="button" class="btn btn-xs btn-primary">Edit</a>
                                            {{Form::open(['route' => ['suppliers.destroy', $item->id], 'class' => 'form-horizontal', 'style' => 'display: -webkit-inline-box'])}}
                                            {{method_field('DELETE')}}
                                            {{Form::button('Delete', ['type' => 'submit', 'class' => 'btn btn-xs btn-danger', 'style' => 'position: relative; top: -5px;', 'onclick' => 'return confirm("You sure to delete this data?")'])}}
                                            {{Form::close()}}
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        {{-- end tabpanel --}}
                        
                        {{-- start tabpanel --}}
                        <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                            {{Form::open(['route' => 'suppliers.store', 'class' => 'form-horizontal form-label-left', 'data-parsley-validate'])}}
                            <div class="form-group">
                                {{Form::label('is_active', 'Is Active?', ['class' => 'control-label col-md-4 col-sm-3 col-xs-12'])}}
                                <div class="col-xs-12 col-sm-12 col-md-4">
                                    {{Form::checkbox('is_active', 1, ['id' => 'is_active'])}}
                                </div>
                            </div>
                            <div class="form-group">
                                {{Form::label('name', 'Name', ['class' => 'control-label col-md-4 col-sm-5 col-xs-12'])}}
                                <div class="col-xs-12 col-sm-12 col-md-4">
                                    {{Form::text('name', NULL, ['id' => 'name', 'class' => 'form-control col-md-7 col-xs-12'])}}
                                </div>
                            </div>
                            <div class="form-group">
                                {{Form::label('address', 'Address', ['class' => 'control-label col-md-4 col-sm-5 col-xs-12'])}}
                                <div class="col-xs-12 col-sm-12 col-md-4">
                                    {{Form::textarea('address', NULL, ['id' => 'address', 'class' => 'form-control col-md-7 col-xs-12', 'rows' => 4])}}
                                </div>
                            </div>
                            <div class="form-group">
                                {{Form::label('province_id', 'Province', ['class' => 'control-label col-md-4 col-sm-5 col-xs-12'])}}
                                <div class="col-xs-12 col-sm-12 col-md-4">
                                    <select name="province_id" id="province_id" class="form-control col-md-7 col-xs-12">
                                        <option>Choose...</option>
                                        @foreach ($provinces as $item)
                                            <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                {{Form::label('phone', 'Phone', ['class' => 'control-label col-md-4 col-sm-5 col-xs-12'])}}
                                <div class="col-xs-12 col-sm-12 col-md-4">
                                    {{Form::text('phone', NULL, ['id' => 'phone', 'class' => 'form-control col-md-7 col-xs-12'])}}
                                </div>
                            </div>
                            <div class="form-group">
                                {{Form::label('email', 'Email', ['class' => 'control-label col-md-4 col-sm-5 col-xs-12'])}}
                                <div class="col-xs-12 col-sm-12 col-md-4">
                                    {{Form::email('email', NULL, ['id' => 'email', 'class' => 'form-control col-md-7 col-xs-12'])}}
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            {{Form::button('Submit', ['type' => 'submit', 'class' => 'btn btn-success'])}}
                            {{Form::close()}}
                        </div>
                        {{-- end tabpanel --}}

                    </div>
                    {{-- end myTabContent --}}

                </div>
                {{-- end x_content --}}

            </div>
            {{-- end x_panel --}}

        </div>
        {{-- end col --}}

    </div>
    {{-- end row --}}

</div>
{{-- end right_col --}}
@endsection

resources/views/supplier/detail.blade.php
@extends('layouts.app')
@section('title', 'POS-SMART | ' .$supplier->name)
@section('supplier_content')
{{-- start right_col --}}
<div class="right_col" role="main">

    {{-- start row --}}
    <div class="row">
        
        {{-- start col --}}
        <div class="col-xs-12 col-sm-12 col-md-12">

            {{-- start breadcrumb --}}
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" style="background: #e9ecef !important;">
                    <li class="breadcrumb-item"><a class="white-text" href="{{route('homes.index')}}">Home</a></li>
                    <li class="breadcrumb-item">Master Data</li>
                    <li class="breadcrumb-item"><a href="{{route('suppliers.index')}}">Suppliers</a></li>
                    <li class="breadcrumb-item"><a href="{{route('suppliers.show', $supplier->id)}}">{{$supplier->name}}</a></li>
                </ol>
            </nav>
            {{-- end breadcrumb --}}

            <!-- Notification -->
            @if (session('notification_error'))
                <div class="alert alert-danger">
                    {!! session('notification_error') !!}
                </div>
            @endif
            @if (session('notification_success'))
                <div class="alert alert-success">
                    {!! session('notification_success') !!}
                </div>
            @endif
                
            <a href="{{route('suppliers.index')}}" class="btn btn-lg btn-default" role="button">Back</a>
            <a href="{{route('suppliers.edit', $supplier->id)}}" class="btn btn-lg btn-primary" role="button">Edit</a>
            {{Form::open(['route' => ['stuffs.destroy', $supplier->id], 'class' => 'form-horizontal', 'style' => 'display: -webkit-inline-box'])}}
            {{method_field('DELETE')}}
            {{Form::button('Delete', ['type' => 'submit', 'class' => 'btn btn-lg btn-danger', 'style' => 'position: relative; top: -15px;', 'onclick' => 'return confirm("You sure to delete this data?")'])}}
            {{Form::close()}}
    
            {{-- start x_panel --}}
            <div class="x_panel">
        
                {{-- start x_title --}}
                <div class="x_title">
        
                    <h1>{!! '<b>'.$supplier->name.'</b>' !!}</h1>
                            
                    <div class="clearfix"></div>
                            
                </div>
                {{-- end x_title --}}
        
                {{-- start x_content --}}
                <div class="x_content">
    
                    {{-- start div --}}
                    <div>
                        <h4>Supplier Information</h4>
                                    
                        <div class="clearfix"></div>   
                    </div>
                    {{-- end div --}}
        
                    <table class="table table-striped table-bordered dt-responsive">
                        <tr>
                            <td style="text-align: right; width: 45%">Is Active?</td>
                            <td>
                                @if ($supplier->is_active == 1)
                                    <span class="btn btn-xs btn-success">Active</span>
                                @else
                                    <span class="btn btn-xs btn-danger">No Active</span>
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align: right;">Name</td>
                            <td>{{$supplier->name}}</td>
                        </tr>
                        <tr>
                            <td style="text-align: right">Address</td>
                            <td>{{$supplier->address}}</td>
                        </tr>
                        <tr>
                            <td style="text-align: right">Province</td>
                            <td>{{$supplier->province->name}}, {{$supplier->province->country->name}}</td>
                        </tr>
                        <tr>
                            <td style="text-align: right">Phone</td>
                            <td>{{$supplier->phone}}</td>
                        </tr>
                        <tr>
                            <td style="text-align: right">Email</td>
                            <td>{{$supplier->email}}</td>
                        </tr>
                    </table>
    
                    {{-- start div --}}
                    <div>
                
                        <h4>Supplier Information II</h4>
                                                
                        <div class="clearfix"></div>   
                    
                    </div>
                    {{-- end div --}}
            
                    <table class="table table-striped table-bordered dt-responsive">
                        <tr>
                            <td style="text-align: right; width: 45%">Created at</td>
                            <td>{{$supplier->created_at}}</td>
                        </tr>
                        <tr>
                            <td style="text-align: right">Updated at</td>
                            <td>{{$supplier->updated_at}}</td>
                        </tr>
                    </table>
        
                </div>
                {{-- end x_content --}}
        
            </div>
            {{-- end x_panel --}}
        
        </div>
        {{-- end col --}}
        
    </div>
    {{-- end row --}}
        
</div>
{{-- end right_col --}}
@endsection

resources/views/supplier/edit.blade.php
@extends('layouts.app')
@section('title', 'POS-SMART | ' .$supplier->name. ' | Edit')
@section('supplier_content')
{{-- start right_col --}}
<div class="right_col" role="main">

    {{-- start row --}}
    <div class="row">
        
        {{-- start col --}}
        <div class="col-xs-12 col-sm-12 col-md-12">
            
            {{-- start breadcrumb --}}
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" style="background: #e9ecef !important;">
                    <li class="breadcrumb-item"><a class="white-text" href="{{route('homes.index')}}">Home</a></li>
                    <li class="breadcrumb-item">Master Data</li>
                    <li class="breadcrumb-item"><a href="{{route('suppliers.index')}}">Suppliers</a></li>
                    <li class="breadcrumb-item"><a href="{{route('suppliers.show', $supplier->id)}}">{{$supplier->name}}</a></li>
                    <li class="breadcrumb-item active">Edit</li>
                </ol>
            </nav>
            {{-- end breadcrumb --}}
    
            {{-- Showing error when running validate process --}}
            @foreach($errors->all() as $message)
                <div class="alert alert-warning">
                    {{$message}}
                </div>
            @endforeach

            {{-- start x_panel --}}
            <div class="x_panel">
        
                {{-- start x_title --}}
                <div class="x_title">
        
                    <h1>{!! '<b>'.$supplier->name.'</b>' !!}</h1>
                            
                    <div class="clearfix"></div>
                            
                </div>
                {{-- end x_title --}}
        
                {{-- start x_content --}}
                <div class="x_content">
    
                    {{-- start div --}}
                    <div>
                        <h4>Supplier Information</h4>
                                    
                        <div class="clearfix"></div>   
                    </div>
                    {{-- end div --}}
        
                    {{Form::model($supplier, ['route' => ['suppliers.update', $supplier->id], 'class' => 'form-horizontal form-label-left', 'data-parsley-validate'])}}
                    {{method_field('PUT')}}
                    <div class="form-group">
                        {{Form::label('is_active', 'Is Active?', ['class' => 'control-label col-md-4 col-sm-3 col-xs-12'])}}
                        <div class="col-xs-12 col-sm-12 col-md-4">
                            {{Form::checkbox('is_active', $supplier->is_active, NULL, ['id' => 'is_active'])}}
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('name', 'Name', ['class' => 'control-label col-md-4 col-sm-5 col-xs-12'])}}
                        <div class="col-xs-12 col-sm-12 col-md-4">
                            {{Form::text('name', NULL, ['id' => 'name', 'class' => 'form-control col-md-7 col-xs-12'])}}
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('address', 'Address', ['class' => 'control-label col-md-4 col-sm-5 col-xs-12'])}}
                        <div class="col-xs-12 col-sm-12 col-md-4">
                            {{Form::textarea('address', NULL, ['id' => 'address', 'class' => 'form-control col-md-7 col-xs-12', 'rows' => 4])}}
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('phone', 'Phone', ['class' => 'control-label col-md-4 col-sm-5 col-xs-12'])}}
                        <div class="col-xs-12 col-sm-12 col-md-4">
                            {{Form::text('phone', NULL, ['id' => 'phone', 'class' => 'form-control col-md-7 col-xs-12'])}}
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('email', 'Email', ['class' => 'control-label col-md-4 col-sm-5 col-xs-12'])}}
                        <div class="col-xs-12 col-sm-12 col-md-4">
                            {{Form::email('email', NULL, ['id' => 'email', 'class' => 'form-control col-md-7 col-xs-12'])}}
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('province_id', 'Province', ['class' => 'control-label col-md-4 col-sm-5 col-xs-12'])}}
                        <div class="col-xs-12 col-sm-12 col-md-4">
                            <select name="province_id" id="province_id" class="form-control col-md-7 col-xs-12">
                                <option>Choose...</option>
                                @foreach ($provinces as $item)
                                    @if ($supplier->province_id == $item->id)
                                    <option value="{{$item->id}}" selected>{{$item->name}}</option>
                                    @else
                                    <option value="{{$item->id}}">{{$item->name}}</option>  
                                    @endif
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    {{Form::button('Submit', ['type' => 'submit', 'class' => 'btn btn-success'])}}
                    <a href="{{route('suppliers.show', $supplier->id)}}" class="btn btn-md btn-default" role="button">Back</a>
                    {{Form::close()}}
        
                </div>
                {{-- end x_content --}}
            
            </div>
            {{-- end x_panel --}}
            
        </div>
        {{-- end col --}}
            
    </div>
    {{-- end row --}}
        
</div>
{{-- end right_col --}}
@endsection